import { StyleSheet } from "react-native";
import { CHILD_THEME } from "../childTheme";

export const taskStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#7a4b28",
    flex: 1,
  },
  header: {
    alignItems: "center",
    backgroundColor: "#7a4b28",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingBottom: 13,
    paddingHorizontal: 17,
    paddingTop: 7,
  },
  eyebrow: { color: "#e0b86a", fontSize: 10, fontWeight: "900", letterSpacing: 2.5 },
  screenTitle: { color: CHILD_THEME.parchment, fontSize: 28, fontWeight: "900", marginTop: 1 },
  wallet: {
    backgroundColor: "#29364a",
    borderColor: "#d5af62",
    borderRadius: 18,
    borderWidth: 2,
    minWidth: 124,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  walletLabel: { color: "#d8ccb4", fontSize: 10, fontWeight: "800", textAlign: "center" },
  walletRow: { alignItems: "center", flexDirection: "row", justifyContent: "center", marginTop: 2 },
  coin: {
    alignItems: "center",
    backgroundColor: CHILD_THEME.brightYellow,
    borderColor: "#fff1aa",
    borderRadius: 10,
    borderWidth: 1,
    height: 20,
    justifyContent: "center",
    marginRight: 5,
    width: 20,
  },
  coinText: { color: "#62400c", fontSize: 11, fontWeight: "900" },
  walletValue: { color: CHILD_THEME.parchment, fontSize: 19, fontWeight: "900" },
  walletUnit: { color: "#e0b86a", fontSize: 10, fontWeight: "900" },
  boardFrame: {
    backgroundColor: "#57432f",
    borderColor: "#9d7950",
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    borderWidth: 4,
    flex: 1,
    marginHorizontal: 9,
    overflow: "hidden",
  },
  frameRivetLeft: {
    backgroundColor: "#d5a84d",
    borderColor: "#513018",
    borderRadius: 5,
    borderWidth: 1,
    height: 10,
    left: 9,
    position: "absolute",
    top: 9,
    width: 10,
    zIndex: 2,
  },
  frameRivetRight: {
    backgroundColor: "#d5a84d",
    borderColor: "#513018",
    borderRadius: 5,
    borderWidth: 1,
    height: 10,
    position: "absolute",
    right: 9,
    top: 9,
    width: 10,
    zIndex: 2,
  },
  tabsRow: {
    backgroundColor: "#57432f",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    flexDirection: "row",
    overflow: "hidden",
  },
  folderTab: {
    alignItems: "center",
    backgroundColor: "#57432f",
    borderLeftColor: "#4c3926",
    borderLeftWidth: 2,
    flex: 1,
    height: 60,
    justifyContent: "center",
  },
  folderTabFirst: { borderLeftWidth: 0 },
  folderTabActive: { backgroundColor: "#e4cd94" },
  folderTabText: { color: "#f3e9d1", fontSize: 16, fontWeight: "900" },
  folderTabTextActive: { color: "#47341f" },
  boardContent: { backgroundColor: "#e4cd94", flex: 1, padding: 10 },
  taskScroll: { flex: 1 },
  // おサイフのチップ（濃紺 #29364a、minWidth 124）の中に収まる短い文言。
  // mockNotice は板の色を前提にした薄い9pxなので、ここでは使わない
  walletErrorNotice: {
    color: "#ffb4a2",
    fontSize: 10,
    fontWeight: "700",
    marginTop: 2,
    textAlign: "center",
  },
  // 取得に失敗したことを伝える文言。板の色（#e4cd94）の上で読める赤にする
  fetchErrorNotice: {
    color: "#9b2c2c",
    fontSize: 12,
    fontWeight: "700",
    paddingVertical: 20,
    textAlign: "center",
  },
  taskScrollContent: { paddingBottom: 8, width: "100%" },
  taskList: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    paddingHorizontal: 4,
    paddingTop: 10,
    width: "100%",
  },
  // クエストボードに貼られた紙をイメージしたカード（Issue #231）。
  // 上端中央のピンで留まっているように見せるため、overflowは隠さない。
  // 幅は3列グリッドになるようTaskListコンポーネント側でpx指定する
  taskCard: {
    backgroundColor: "#f8efd6",
    borderRadius: 12,
    elevation: 3,
    marginBottom: 14,
    marginTop: 8,
    minHeight: 108,
    paddingBottom: 10,
    paddingHorizontal: 8,
    paddingTop: 18,
    position: "relative",
    shadowColor: "#4a321d",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  taskCardSelected: { backgroundColor: "#fff9e8" },
  taskCardPressed: { backgroundColor: "#ecdfbd" },
  taskCardPin: {
    backgroundColor: "#8a8f99",
    borderColor: "#3a3d42",
    borderRadius: 6,
    borderWidth: 1,
    height: 12,
    left: "50%",
    marginLeft: -6,
    position: "absolute",
    top: -6,
    width: 12,
    zIndex: 2,
  },
  taskCardTitle: { color: "#30271d", fontSize: 13, fontWeight: "900", textAlign: "center" },
  taskCardFooter: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    justifyContent: "center",
    marginTop: 8,
    width: "100%",
  },
  rewardValue: { color: "#654313", fontSize: 12, fontWeight: "900" },
  rewardUnit: { color: "#76541f", fontSize: 8, fontWeight: "900" },
  statusBadge: {
    alignItems: "center",
    backgroundColor: "#eee4cc",
    borderRadius: 2,
    borderWidth: 2,
    justifyContent: "center",
    paddingHorizontal: 4,
    paddingVertical: 3,
  },
  statusOpen: { borderColor: "#817b70" },
  statusAccepted: { borderColor: "#3478a8" },
  statusPending: { borderColor: "#b17a17" },
  statusCompleted: { borderColor: "#557b4a" },
  statusText: { fontSize: 9, fontWeight: "900", textAlign: "center" },
  statusTextDark: { color: "#493d2c" },
  statusTextLight: { color: "#493d2c" },
  // heightは呼び出し側（ChildTasksScreen）が板の実測高さから計算して渡す。
  // 固定高さにすることで、詳細を開いたまま別のタスクへ切り替えても
  // 一覧側の下余白（paddingBottom）を再計算せずに済む
  detailPanel: {
    backgroundColor: "#fff8e5",
    borderColor: "#87643a",
    borderRadius: 8,
    borderWidth: 2,
    bottom: 10,
    left: 10,
    padding: 14,
    position: "absolute",
    right: 10,
    shadowColor: "#4a321d",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  // 高さが固定のため、説明文が長い場合はここで内部スクロールさせる
  detailScroll: { flex: 1 },
  closeButton: {
    alignItems: "center",
    backgroundColor: "#fff8e5",
    borderColor: CHILD_THEME.shadow,
    borderRadius: 16,
    borderWidth: 2,
    elevation: 6,
    height: 32,
    justifyContent: "center",
    left: 8,
    position: "absolute",
    shadowColor: CHILD_THEME.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 3,
    top: 8,
    width: 32,
    zIndex: 2,
  },
  closeButtonPressed: { opacity: 0.65, transform: [{ scale: 0.94 }] },
  closeButtonText: { color: CHILD_THEME.shadow, fontSize: 23, fontWeight: "900", lineHeight: 25 },
  detailPinRight: {
    backgroundColor: "#b38442",
    borderRadius: 5,
    height: 9,
    position: "absolute",
    right: 8,
    top: 8,
    width: 9,
  },
  detailLabel: { color: "#97703c", fontSize: 10, fontWeight: "900", letterSpacing: 1, textAlign: "center" },
  detailTitleRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  detailTitle: { color: "#36291d", flex: 1, fontSize: 18, fontWeight: "900", paddingRight: 8 },
  detailReward: {
    alignItems: "baseline",
    backgroundColor: "#f2d586",
    borderColor: "#91672b",
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: "row",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  detailRewardValue: { color: "#69410e", fontSize: 16, fontWeight: "900" },
  detailRewardUnit: { color: "#80571e", fontSize: 10, fontWeight: "900" },
  divider: { backgroundColor: "#d5bd8c", height: 1, marginVertical: 10 },
  descriptionLabel: { color: "#8c6638", fontSize: 11, fontWeight: "900" },
  description: { color: "#4d4031", fontSize: 13, lineHeight: 19, marginTop: 4 },
  currentStatus: { color: "#75634d", fontSize: 11, fontWeight: "700", marginTop: 8 },
  actionRow: { flexDirection: "row", gap: 9, marginTop: 13 },
  actionButton: { alignItems: "center", borderRadius: 9, flex: 1, paddingVertical: 11 },
  acceptButton: { backgroundColor: "#397bab", borderColor: "#245473", borderWidth: 2 },
  reportButton: { backgroundColor: "#c57d35", borderColor: "#805020", borderWidth: 2 },
  actionButtonDisabled: { backgroundColor: "#d2cdc2", borderColor: "#aaa49a" },
  actionButtonText: { color: "#ffffff", fontSize: 14, fontWeight: "900" },
  actionButtonTextDisabled: { color: "#8d8981" },
  mockNotice: { color: "#a09584", fontSize: 9, marginTop: 6, textAlign: "center" },
  footer: {
    alignItems: "center",
    backgroundColor: "#7a4b28",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 11,
  },
  backButton: {
    alignItems: "center",
    borderColor: CHILD_THEME.fadedBeige,
    borderRadius: 10,
    borderWidth: 2,
    flexDirection: "row",
    minWidth: 122,
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  backButtonPressed: { opacity: 0.7, transform: [{ scale: 0.97 }] },
  backArrow: { color: CHILD_THEME.parchment, fontSize: 30, fontWeight: "800", lineHeight: 22, marginRight: 8 },
  backText: { color: CHILD_THEME.parchment, fontSize: 18, fontWeight: "800" },
  footerReportButton: {
    alignItems: "center",
    backgroundColor: CHILD_THEME.gold,
    borderColor: CHILD_THEME.paleYellow,
    borderRadius: 10,
    borderWidth: 2,
    minWidth: 126,
    paddingHorizontal: 26,
    paddingVertical: 12,
  },
  footerReportButtonText: { color: CHILD_THEME.darkWood, fontSize: 17, fontWeight: "900", letterSpacing: 3 },
});
