import { StyleSheet } from "react-native";

export const taskStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#17202c" },
  header: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingBottom: 13,
    paddingHorizontal: 17,
    paddingTop: 7,
  },
  eyebrow: { color: "#e0b86a", fontSize: 10, fontWeight: "900", letterSpacing: 2.5 },
  screenTitle: { color: "#fff8de", fontSize: 28, fontWeight: "900", marginTop: 1 },
  wallet: {
    backgroundColor: "#29364a",
    borderColor: "#d5af62",
    borderRadius: 18,
    borderWidth: 2,
    minWidth: 124,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  walletLabel: { color: "#d8ccb4", fontSize: 10, fontWeight: "800", textAlign: "center" },
  walletRow: { alignItems: "center", flexDirection: "row", justifyContent: "center", marginTop: 2 },
  coin: {
    alignItems: "center",
    backgroundColor: "#f2c94c",
    borderColor: "#fff1aa",
    borderRadius: 10,
    borderWidth: 1,
    height: 20,
    justifyContent: "center",
    marginRight: 5,
    width: 20,
  },
  coinText: { color: "#62400c", fontSize: 11, fontWeight: "900" },
  walletValue: { color: "#fff8de", fontSize: 19, fontWeight: "900" },
  walletUnit: { color: "#e0b86a", fontSize: 10, fontWeight: "900" },
  boardFrame: {
    backgroundColor: "#57432f",
    borderColor: "#9d7950",
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    borderWidth: 4,
    flex: 1,
    marginHorizontal: 9,
    overflow: "hidden",
  },
  tabsRow: {
    alignItems: "flex-end",
    backgroundColor: "#253145",
    flexDirection: "row",
    gap: 3,
    paddingHorizontal: 7,
    paddingTop: 12,
  },
  folderTab: {
    alignItems: "center",
    backgroundColor: "#8d7454",
    borderColor: "#4c3926",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderWidth: 2,
    flex: 1,
    height: 42,
    justifyContent: "center",
    position: "relative",
  },
  folderTabActive: { backgroundColor: "#e4cd94", borderBottomColor: "#e4cd94", height: 49 },
  folderTabTop: {
    backgroundColor: "#8d7454",
    borderColor: "#4c3926",
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderWidth: 2,
    height: 8,
    left: 8,
    position: "absolute",
    top: -8,
    width: 36,
  },
  folderTabTopActive: { backgroundColor: "#e4cd94" },
  folderTabText: { color: "#f3e9d1", fontSize: 12, fontWeight: "900" },
  folderTabTextActive: { color: "#47341f", fontSize: 13 },
  boardContent: { backgroundColor: "#e4cd94", flex: 1, padding: 10 },
  taskScroll: { flex: 1 },
  taskScrollContent: { paddingBottom: 8, width: "100%" },
  taskList: {
    gap: 14,
    paddingHorizontal: 4,
    width: "100%",
  },
  listHeadingRow: {
    alignItems: "center",
    backgroundColor: "#ead8ad",
    borderColor: "#6f5638",
    borderRadius: 3,
    borderWidth: 2,
    flexDirection: "row",
    height: 38,
    overflow: "hidden",
    width: "100%",
  },
  listHeading: {
    color: "#493821",
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
  },
  titleHeading: { textAlign: "left" },
  headingCell: { alignItems: "center", alignSelf: "stretch", justifyContent: "center" },
  headingColumnDivider: { borderLeftColor: "#b69d70", borderLeftWidth: 1 },
  columnDivider: { borderLeftColor: "#d5c39c", borderLeftWidth: 1 },
  titleColumn: { flex: 1, minWidth: 0 },
  rewardColumn: { flexGrow: 0, flexShrink: 0, width: 72 },
  statusColumn: { flexGrow: 0, flexShrink: 0, width: 76 },
  taskRow: {
    backgroundColor: "#f8efd6",
    borderColor: "#2f2217",
    borderRadius: 2,
    borderWidth: 3,
    height: 74,
    overflow: "hidden",
    width: "100%",
  },
  taskRowContent: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    flexWrap: "nowrap",
    height: "100%",
    width: "100%",
  },
  taskRowSelected: { backgroundColor: "#fff9e8", borderColor: "#b16f1e", borderWidth: 3 },
  taskRowPressed: { backgroundColor: "#ecdfbd" },
  titleCell: { alignSelf: "stretch", justifyContent: "center", paddingLeft: 16 },
  taskTitle: { color: "#30271d", fontSize: 14, fontWeight: "900" },
  rewardCell: {
    alignItems: "center",
    alignSelf: "stretch",
    justifyContent: "center",
  },
  rewardValue: { color: "#654313", fontSize: 14, fontWeight: "900" },
  rewardUnit: { color: "#76541f", fontSize: 9, fontWeight: "900" },
  statusCell: { alignItems: "center", alignSelf: "stretch", justifyContent: "center" },
  statusBadge: {
    alignItems: "center",
    backgroundColor: "#eee4cc",
    borderRadius: 2,
    borderWidth: 2,
    justifyContent: "center",
    minHeight: 30,
    minWidth: 66,
    paddingHorizontal: 3,
  },
  statusOpen: { borderColor: "#817b70" },
  statusAccepted: { borderColor: "#3478a8" },
  statusPending: { borderColor: "#b17a17" },
  statusCompleted: { borderColor: "#557b4a" },
  statusText: { fontSize: 10, fontWeight: "900", textAlign: "center" },
  statusTextDark: { color: "#493d2c" },
  statusTextLight: { color: "#493d2c" },
  detailPanel: {
    backgroundColor: "#fff8e5",
    borderColor: "#87643a",
    borderRadius: 8,
    borderWidth: 2,
    marginTop: 12,
    minHeight: 235,
    padding: 14,
    position: "relative",
    shadowColor: "#4a321d",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: "#fff8e5",
    borderColor: "#000000",
    borderRadius: 16,
    borderWidth: 2,
    elevation: 6,
    height: 32,
    justifyContent: "center",
    left: 8,
    position: "absolute",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 3,
    top: 8,
    width: 32,
    zIndex: 2,
  },
  closeButtonPressed: { opacity: 0.65, transform: [{ scale: 0.94 }] },
  closeButtonText: { color: "#000000", fontSize: 23, fontWeight: "900", lineHeight: 25 },
  detailPinRight: {
    backgroundColor: "#b38442",
    borderRadius: 5,
    height: 9,
    position: "absolute",
    right: 8,
    top: 8,
    width: 9,
  },
  detailLabel: { color: "#97703c", fontSize: 10, fontWeight: "900", letterSpacing: 1, textAlign: "center" },
  detailTitleRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  detailTitle: { color: "#36291d", flex: 1, fontSize: 18, fontWeight: "900", paddingRight: 8 },
  detailReward: {
    alignItems: "baseline",
    backgroundColor: "#f2d586",
    borderColor: "#91672b",
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: "row",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  detailRewardValue: { color: "#69410e", fontSize: 16, fontWeight: "900" },
  detailRewardUnit: { color: "#80571e", fontSize: 10, fontWeight: "900" },
  divider: { backgroundColor: "#d5bd8c", height: 1, marginVertical: 10 },
  descriptionLabel: { color: "#8c6638", fontSize: 11, fontWeight: "900" },
  description: { color: "#4d4031", fontSize: 13, lineHeight: 19, marginTop: 4 },
  currentStatus: { color: "#75634d", fontSize: 11, fontWeight: "700", marginTop: 8 },
  actionRow: { flexDirection: "row", gap: 9, marginTop: 13 },
  actionButton: { alignItems: "center", borderRadius: 9, flex: 1, paddingVertical: 11 },
  acceptButton: { backgroundColor: "#397bab", borderColor: "#245473", borderWidth: 2 },
  reportButton: { backgroundColor: "#c57d35", borderColor: "#805020", borderWidth: 2 },
  actionButtonDisabled: { backgroundColor: "#d2cdc2", borderColor: "#aaa49a" },
  actionButtonText: { color: "#ffffff", fontSize: 14, fontWeight: "900" },
  actionButtonTextDisabled: { color: "#8d8981" },
  mockNotice: { color: "#a09584", fontSize: 9, marginTop: 6, textAlign: "center" },
  footer: { backgroundColor: "#17202c", paddingHorizontal: 16, paddingTop: 11 },
  backButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    borderColor: "#c2aa80",
    borderRadius: 10,
    borderWidth: 2,
    flexDirection: "row",
    minWidth: 122,
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  backButtonPressed: { opacity: 0.7, transform: [{ scale: 0.97 }] },
  backArrow: { color: "#fff8de", fontSize: 30, fontWeight: "800", lineHeight: 22, marginRight: 8 },
  backText: { color: "#fff8de", fontSize: 18, fontWeight: "800" },
});
