import { StyleSheet } from "react-native";
import { CHILD_THEME } from "../childTheme";

export const storeStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#171220" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingBottom: 14,
    paddingTop: 8,
  },
  eyebrow: { color: CHILD_THEME.gold, fontSize: 10, fontWeight: "800", letterSpacing: 2 },
  screenTitle: {
    color: CHILD_THEME.parchment,
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: 1,
    marginTop: 2,
  },
  balanceBadge: {
    backgroundColor: "#2a2135",
    borderColor: CHILD_THEME.gold,
    borderRadius: 18,
    borderWidth: 2,
    minWidth: 118,
    paddingHorizontal: 13,
    paddingVertical: 7,
  },
  balanceLabel: { color: "#c7bca8", fontSize: 10, fontWeight: "700", textAlign: "center" },
  balanceRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 2,
  },
  coin: {
    alignItems: "center",
    backgroundColor: CHILD_THEME.brightYellow,
    borderColor: CHILD_THEME.paleYellow,
    borderRadius: 10,
    borderWidth: 1,
    height: 20,
    justifyContent: "center",
    marginRight: 6,
    width: 20,
  },
  coinText: { color: "#68440d", fontSize: 11, fontWeight: "900" },
  balanceValue: { color: CHILD_THEME.parchment, fontSize: 20, fontWeight: "900" },
  shopFrame: {
    backgroundColor: "#5b321f",
    borderColor: "#9b6338",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 5,
    flex: 1,
    marginHorizontal: 10,
    overflow: "hidden",
  },
  frameRivetLeft: {
    backgroundColor: "#d5a84d",
    borderColor: "#513018",
    borderRadius: 5,
    borderWidth: 1,
    height: 10,
    left: 9,
    position: "absolute",
    top: 9,
    width: 10,
    zIndex: 2,
  },
  frameRivetRight: {
    backgroundColor: "#d5a84d",
    borderColor: "#513018",
    borderRadius: 5,
    borderWidth: 1,
    height: 10,
    position: "absolute",
    right: 9,
    top: 9,
    width: 10,
    zIndex: 2,
  },
  shopContent: {
    backgroundColor: "#2b1b25",
    flex: 1,
    paddingBottom: 14,
    paddingHorizontal: 10,
    paddingTop: 16,
  },
  shopScene: {
    borderRadius: 12,
    flex: 1,
    marginBottom: 10,
    overflow: "hidden",
  },
  shopSign: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#d9b978",
    borderColor: "#6d3f24",
    borderRadius: 8,
    borderWidth: 3,
    marginBottom: 14,
    paddingHorizontal: 34,
    paddingVertical: 7,
    transform: [{ rotate: "-1deg" }],
  },
  shopSignText: { color: CHILD_THEME.darkWood, fontSize: 18, fontWeight: "900", letterSpacing: 4 },
  shopSubtext: { color: "#69462d", fontSize: 10, fontWeight: "700", marginTop: 1 },
  guideText: {
    color: "#cbbd9f",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
    textAlign: "center",
  },
  emptyState: { alignItems: "center", paddingVertical: 40 },
  emptyStateText: { color: "#cbbd9f", fontSize: 13, fontWeight: "700", textAlign: "center" },
  detailPanel: {
    backgroundColor: "#2a2135",
    borderColor: CHILD_THEME.gold,
    borderRadius: 20,
    borderWidth: 3,
    elevation: 14,
    height: "56%",
    left: 12,
    padding: 16,
    position: "absolute",
    right: 12,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.55,
    shadowRadius: 12,
    top: 12,
    zIndex: 5,
  },
  detailContent: {
    flex: 1,
    flexDirection: "row",
    gap: 16,
  },
  detailCloseButton: {
    alignItems: "center",
    backgroundColor: "#17121b",
    borderColor: CHILD_THEME.gold,
    borderRadius: 14,
    borderWidth: 2,
    height: 28,
    justifyContent: "center",
    position: "absolute",
    right: 10,
    top: 10,
    width: 28,
    zIndex: 3,
  },
  detailImage: {
    backgroundColor: "#17121b",
    borderColor: CHILD_THEME.gold,
    borderRadius: 14,
    borderWidth: 2,
    height: "100%",
    width: "40%",
  },
  detailInfo: { flex: 1, justifyContent: "center" },
  detailTitle: { color: CHILD_THEME.parchment, fontSize: 22, fontWeight: "900" },
  detailDescription: { color: "#c7bca8", fontSize: 14, fontWeight: "600", marginTop: 8 },
  detailMetaRow: {
    flexDirection: "row",
    gap: 20,
    marginTop: 16,
  },
  detailPrice: { color: CHILD_THEME.brightYellow, fontSize: 20, fontWeight: "900" },
  detailStock: { color: "#c7bca8", fontSize: 16, fontWeight: "700" },
  detailPurchaseButton: {
    alignItems: "center",
    backgroundColor: "#6f6350",
    borderColor: "#a99a7e",
    borderRadius: 10,
    borderWidth: 2,
    marginTop: 12,
    opacity: 0.7,
    paddingVertical: 10,
  },
  detailPurchaseButtonText: {
    color: "#ddd3bd",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 2,
    textAlign: "center",
  },
  footer: {
    alignItems: "center",
    backgroundColor: "#171220",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  backButton: {
    alignItems: "center",
    borderColor: CHILD_THEME.fadedBeige,
    borderRadius: 10,
    borderWidth: 2,
    flexDirection: "row",
    minWidth: 122,
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  backArrow: {
    color: CHILD_THEME.parchment,
    fontSize: 30,
    fontWeight: "800",
    lineHeight: 22,
    marginRight: 8,
  },
  backButtonText: { color: CHILD_THEME.parchment, fontSize: 18, fontWeight: "800" },
  requestFooterButton: {
    alignItems: "center",
    backgroundColor: "#2a2135",
    borderColor: "#d6b66a",
    borderRadius: 10,
    borderWidth: 2,
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  requestFooterButtonText: { color: "#fff8de", fontSize: 15, fontWeight: "900" },
  footerButtonPressed: { opacity: 0.7, transform: [{ scale: 0.97 }] },
  modalBackdrop: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.6)",
    flex: 1,
    justifyContent: "center",
    padding: 24,
  },
  modalCard: {
    backgroundColor: "#2a2135",
    borderColor: "#d6b66a",
    borderRadius: 18,
    borderWidth: 3,
    padding: 20,
    width: "100%",
  },
  modalImage: {
    backgroundColor: "#17121b",
    borderColor: "#d6b66a",
    borderRadius: 14,
    borderWidth: 2,
    height: 140,
    marginBottom: 12,
    width: "100%",
  },
  modalTitle: { color: "#fff8de", fontSize: 18, fontWeight: "900", marginBottom: 6 },
  modalDescription: { color: "#cbbd9f", fontSize: 13, lineHeight: 18, marginBottom: 14 },
  modalRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  modalRowLabel: { color: "#c7bca8", fontSize: 12, fontWeight: "700" },
  modalRowValue: { color: "#fff8de", fontSize: 14, fontWeight: "900" },
  modalButton: {
    alignItems: "center",
    borderRadius: 12,
    marginTop: 16,
    paddingVertical: 13,
  },
  modalButtonEnabled: { backgroundColor: "#d6b66a" },
  modalButtonDisabled: { backgroundColor: "#4a4256" },
  modalButtonText: { fontSize: 15, fontWeight: "900" },
  modalButtonTextEnabled: { color: "#2a1f10" },
  modalButtonTextDisabled: { color: "#8d8896" },
  modalCancelButton: { alignItems: "center", marginTop: 10, paddingVertical: 8 },
  modalCancelButtonText: { color: "#a79cc2", fontSize: 13, fontWeight: "700" },
  modalErrorText: { color: "#f28b82", fontSize: 12, fontWeight: "700", marginTop: 8, textAlign: "center" },
  modalSuccessText: {
    color: "#8bd8a0",
    fontSize: 15,
    fontWeight: "900",
    marginTop: 16,
    textAlign: "center",
  },
  errorState: { alignItems: "center", gap: 12, paddingVertical: 40 },
  errorStateText: { color: "#f28b82", fontSize: 13, fontWeight: "700", textAlign: "center" },
  errorRetryButton: { backgroundColor: "#d6b66a", borderRadius: 10, paddingHorizontal: 24, paddingVertical: 10 },
  errorRetryButtonText: { color: "#2a1f10", fontSize: 14, fontWeight: "900" },
});
